PRINT "=== 1. TEST DES TYPES ENTIERS ET FLOTTANTS ==="
LET ENT = 42
LET FLOT = 3.1415
PRINT "Entier : ", : PRINT ENT
PRINT "Flottant : ", : PRINT FLOT

PRINT "=== 2. ARITHMETIQUE PURE ENTIERE ==="
LET SOMME = 10 + 20 * 2
PRINT "10 + 20 * 2 (Entier pur) = ", : PRINT SOMME

PRINT "=== 3. ARITHMETIQUE MIXTE (COERCITION AUTO) ==="
LET MIXTE = ENT + FLOT
PRINT "42 + 3.1415 = ", : PRINT MIXTE

PRINT "=== 4. TEST DES BOOLEENS ET CONDITIONS ==="
LET B1 = TRUE
LET B2 = FALSE
PRINT "B1 = ", : PRINT B1
PRINT "B2 = ", : PRINT B2

LET COND = (ENT > 10)
PRINT "42 > 10 est ", : PRINT COND

IF COND THEN PRINT "Condition Verifiee avec succes !" ELSE PRINT "Erreur"
IF 42 = 42 THEN PRINT "Egalite entiere OK"

PRINT "=== 5. BOUCLE FOR ENTIERE (SANS DECIMALES) ==="
FOR I = 1 TO 5 STEP 1
  PRINT I,
NEXT I
PRINT ""

PRINT "=== FIN DU TEST DES TYPES ==="
END