PRINT "=== 1. TEST FONCTIONS MATHEMATIQUES ==="
LET X = -15
PRINT "ABS(-15) = "; ABS(X)
PRINT "INT(3.89) = "; INT(3.89)
PRINT "SQR(144) = "; SQR(144)
PRINT "COS(0) = "; COS(0)
PRINT "SIN(0) = "; SIN(0)
PRINT "RND(100) (Entier entre 0 et 99) = "; RND(100)

PRINT "=== 2. TEST FONCTIONS DE CHAINES ==="
LET PHRASE$ = "NanoBasic 2026"
PRINT "Chaine : ["; PHRASE$; "]"
PRINT "LEN(PHRASE$) = "; LEN(PHRASE$)
PRINT "LEFT$(PHRASE$, 4) = "; LEFT$(PHRASE$, 4)
PRINT "RIGHT$(PHRASE$, 4) = "; RIGHT$(PHRASE$, 4)
PRINT "MID$(PHRASE$, 5, 5) = "; MID$(PHRASE$, 5, 5)

PRINT "=== 3. TEST CONVERSIONS ASCII & NOMBRES ==="
PRINT "CHR$(65) = "; CHR$(65)
PRINT "ASC(\"Z\") = "; ASC("Z")

LET NUM_STR$ = "12345"
LET NOMBRE = VAL(NUM_STR$)
PRINT "VAL(\"12345\") + 5 = "; NOMBRE + 5
PRINT "STR$(3.14) = "; STR$(3.14)

PRINT "=== FIN DU TEST DES FONCTIONS ==="
END